PINUS_APP = neuron_spikesourcepoisson

# Build object list
SOURCES = ../common/config.cpp \
	../common/bit_field.cpp \
	../common/profiler.cpp \
	spike_source_poisson.cpp

CFLAGS += -I $(CURDIR)

include ../Makefile.depend