PINUS_APP = current_input_spikesourcepoisson

# Build object list
SOURCES = ../common/config.cpp \
	../common/bit_field.cpp \
	../common/profiler.cpp \
	current_input_poisson.cpp

CFLAGS += -I $(CURDIR)

include ../Makefile.depend